# Generated by Django 5.2.3 on 2025-07-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0003_rename_image_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
