name: Build, Test and Deploy Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v2
    - name: Injecting environment vars
      run: |
        echo "SECRET_KEY=test_foo
        DATABASE_NAME=coredb
        DATABASE_USER=core
        DATABASE_PASSWORD=123
        DATABASE_HOST=postagram_db
        DATABASE_PORT=5432
        POSTGRES_USER=core
        POSTGRES_PASSWORD=123
        POSTGRES_DB=coredb
        ENV=TESTING
        DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
          " >> .env
    - name: Building Docker containers
      run: |
        docker compose up -d --build
    - name: Running Tests inside Docker containers
      run: |
        docker compose run --rm api pytest

  deploy:
      name: Deploying on EC2 via SSH
      defaults:
        run:
          working-directory: backend
      if: ${{ github.event_name == 'push' }}
      needs: [build-test]
      runs-on: ubuntu-latest
      steps:
      - name: Deploying Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_EC2_IP }}
          username: ${{ secrets.SSH_EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/.scripts
            ./docker-ec2-deploy.sh
